# Generated by Django 6.0.8 on 2026-09-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_organization_admin_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidluser',
            name='teams_channel_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aidluser',
            name='teams_channel_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='aidluser',
            name='teams_team_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='organization',
            name='teams_welcome_channel_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='teams_welcome_message_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
