# Generated by Django 6.0.8 on 2026-09-08 08:35

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_organization_admin_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDelivery',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=64)),
                ('card_key', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('not_sent', 'Not sent'), ('sent', 'Sent'), ('scheduled', 'Scheduled')], default='not_sent', max_length=16)),
                ('purchased', models.BooleanField(default=False)),
                ('lights', models.CharField(blank=True, default='', max_length=32)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['card_key'],
            },
        ),
        migrations.CreateModel(
            name='CardRequest',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('standard', 'Standard'), ('urgent', 'Urgent')], default='standard', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('scoped', 'Scoped'), ('done', 'Delivered')], default='pending', max_length=16)),
                ('requested_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aidluser',
            name='teams_channel_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aidluser',
            name='teams_channel_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='aidluser',
            name='teams_team_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='organization',
            name='admin_card_channel_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='admin_card_message_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='admin_card_sent',
            field=models.BooleanField(default=False),
        ),
    ]
