# Generated by Django 6.0.8 on 2026-09-15 13:57

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_teams_channel_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('learner', 'Learner')], default='learner', max_length=32)),
                ('organization_id', models.CharField(db_index=True, max_length=64)),
                ('organization_name', models.CharField(blank=True, default='', max_length=255)),
                ('invited_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('team_member_added', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aidluser',
            name='ms_refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
