# Generated by Django 6.0.8 on 2026-09-17 15:06

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_invitation_aidluser_ms_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCustomRequest',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=64)),
                ('requested_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='submitted', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardRequest',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=64)),
                ('card_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('sent', 'Sent'), ('scheduled', 'Scheduled'), ('failed', 'Failed')], default='requested', max_length=16)),
                ('requested_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=64)),
                ('file_name', models.CharField(max_length=255)),
                ('file_content_type', models.CharField(default='application/pdf', max_length=100)),
                ('file_base64', models.TextField()),
                ('version', models.CharField(blank=True, default='', max_length=32)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('uploaded_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('uploaded_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_live', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aidluser',
            name='perm_access_cards',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aidluser',
            name='perm_approve_apps',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aidluser',
            name='perm_create_card',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='registeredapp',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registeredapp',
            name='data_allowed',
            field=models.CharField(blank=True, choices=[('public_only', 'Public only'), ('internal', 'Internal'), ('internal_confidential', 'Internal + Confidential'), ('none', 'None')], default='', max_length=32),
        ),
    ]
