# Generated by Django 6.0.8 on 2026-09-18 13:27

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cardcustomrequest_cardrequest_policyversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLightRating',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=128)),
                ('dislikes', models.IntegerField(default=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='aidluser',
            name='licence_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aidluser',
            name='licence_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aidluser',
            name='licence_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
