# Generated by Django 6.0.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_trafficlightrating_aidluser_licence_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bot_service_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='bot_tenant_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
