# Generated by Django 6.0.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_organization_bot_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="aidluser",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="aidluser",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="aidluser",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="aidluser",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="aidluser",
            name="license_class",
            field=models.CharField(
                blank=True,
                choices=[("class_l", "Class L · Learner's Permit")],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="aidluser",
            name="mobile_number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="aidluser",
            name="password_hash",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="aidluser",
            name="state",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
