# Generated by Django 6.0.8 on 2026-09-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_aidluser_website_signup_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slack_team_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
