# Generated by Django 6.0.8 on 2026-09-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_organization_slack_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slack_bot_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='slack_bot_user_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='organization',
            name='slack_channel_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='organization',
            name='slack_home_message_ts',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
