# Generated by Django 6.0.8 on 2026-09-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_organization_slack_install'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthstate',
            name='payload',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='policy_answers',
            field=models.TextField(blank=True, default=''),
        ),
    ]
