# Generated by Django 6.0.8 on 2026-09-28 09:43

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_policy_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLightVote',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=64)),
                ('message_ts', models.CharField(max_length=32)),
                ('slack_user_id', models.CharField(max_length=32)),
                ('vote', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('organization_id', 'message_ts', 'slack_user_id')},
            },
        ),
    ]
