# Generated by Django 6.0.8 on 2026-09-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_traffic_light_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidluser',
            name='slack_admin_card_ts',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='aidluser',
            name='slack_dm_channel_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
