# Generated by Django 6.0.8 on 2026-09-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_admin_card_dm'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrequest',
            name='lights',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
