# Generated by Django 6.0.8 on 2026-10-01 12:07

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_cardrequest_lights'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidluser',
            name='slack_onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Acknowledgement',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=64)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('item', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('user_id', 'item', 'version')},
            },
        ),
    ]
