# Generated by Django 6.0.8 on 2026-10-06 12:34

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_acknowledgement_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidluser',
            name='slack_left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.CharField(default='trial', max_length=16),
        ),
        migrations.CreateModel(
            name='PackageDelivery',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=64)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('package', models.CharField(max_length=16)),
                ('card_no', models.CharField(max_length=8)),
                ('post_order', models.IntegerField()),
                ('post_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='scheduled', max_length=16)),
                ('slack_channel_id', models.CharField(blank=True, default='', max_length=32)),
                ('scheduled_message_id', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['post_at'],
                'unique_together': {('user_id', 'card_no')},
            },
        ),
    ]
