# Generated by Django 6.0.8 on 2026-10-08 04:13

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_plans_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthChallenge',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('captcha', 'Captcha'), ('otp', 'Email code')], max_length=16)),
                ('purpose', models.CharField(blank=True, default='', max_length=16)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('user_id', models.CharField(blank=True, default='', max_length=64)),
                ('answer_hash', models.CharField(max_length=64)),
                ('attempts', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
