# Generated by Django 6.0.8 on 2026-10-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auth_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='owner_user_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
