# Generated by Django 6.0.8 on 2026-10-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_organization_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidluser',
            name='perm_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='setup_state',
            field=models.TextField(blank=True, default=''),
        ),
    ]
